namespace: default

# Replica count for the frontend deployment
replicaCount: 2

# name of resources such as deployment, container, service
name: frontend

# Image repository and tag for the frontend container
image:
  #repository: trongngai/frontend
  repository: ngaitodemoacr.azurecr.io/frontend
  tag: 16

# Port for the frontend service
servicePort: 3000