apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo-preview
spec:
  type: NodePort
  selector:
    app: bluegreen-demo
  ports:
      - nodePort: 30001
        protocol: TCP
        port: 3000
