apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo
spec:
  type: NodePort
  selector:
    app: bluegreen-demo
  ports:
      - nodePort: 30000
        protocol: TCP
        port: 3000